@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor main_cliente

main_cliente -> ProtocoloCliente :  new(hostname, servname)
ProtocoloCliente -> ProtocoloCliente :: Initialize
main_cliente -> ProtocoloCliente :: enviar_mensaje(mensaje)

ProtocoloCliente -> ProtocoloCliente :: tokenizar_linea(mensaje)
ProtocoloCliente --> ProtocoloCliente :: tokens
ProtocoloCliente -> ProtocoloCliente :: serializar_acciones(tokens)
activate ProtocoloCliente #darksalmon
ProtocoloCliente --> ProtocoloCliente : acciones
deactivate ProtocoloCliente
ProtocoloCliente -> "Socket : skt" :: sendall(acciones)
"Socket : skt" -> Server : acciones

@enduml